#!/bin/bash

# Environment Variables Setup Guide for Vercel
# This script provides instructions for setting up environment variables in Vercel

echo "🔧 Environment Variables Setup Guide for Vercel"
echo "================================================"
echo ""
echo "Your EternalGames Jira application has been successfully deployed to Vercel!"
echo ""
echo "📍 Deployment URL: https://eternalgames-jira-456d4vt3j-mehmet-umut-kocs-projects.vercel.app"
echo ""
echo "⚠️  IMPORTANT: You need to set up environment variables in Vercel for the app to work properly."
echo ""
echo "🔗 Go to: https://vercel.com/mehmet-umut-kocs-projects/eternalgames-jira/settings/environment-variables"
echo ""
echo "📝 Set these environment variables:"
echo ""
echo "1. NODE_ENV = production"
echo "2. JWT_SECRET = $(openssl rand -hex 32)"
echo "3. EMAIL_USER = your-email@gmail.com"
echo "4. EMAIL_PASS = your-gmail-app-password"
echo "5. EMAIL_FROM = your-email@gmail.com"
echo "6. FRONTEND_URL = https://eternalgames-jira-456d4vt3j-mehmet-umut-kocs-projects.vercel.app"
echo ""
echo "📧 For Gmail Setup:"
echo "1. Enable 2-factor authentication"
echo "2. Generate App Password: https://myaccount.google.com/apppasswords"
echo "3. Use the app password (not your regular password)"
echo ""
echo "🎛️ Optional Environment Variables:"
echo "MAX_FILE_SIZE = 5242880"
echo "MAX_FILES_PER_TASK = 3"
echo "RATE_LIMIT_MAX = 200"
echo "RATE_LIMIT_WINDOW = 900000"
echo ""
echo "🔄 After setting environment variables:"
echo "1. Redeploy your application"
echo "2. Test the API endpoints"
echo "3. Check if login/register works"
echo ""
echo "🚨 Important Notes:"
echo "- SQLite database is NOT persistent on Vercel"
echo "- Database will reset on every deployment"
echo "- For production, use external database (Railway, PlanetScale, etc.)"
echo ""
echo "📋 Quick Test Commands:"
echo "curl https://eternalgames-jira-456d4vt3j-mehmet-umut-kocs-projects.vercel.app/api/health"
echo "curl -X POST https://eternalgames-jira-456d4vt3j-mehmet-umut-kocs-projects.vercel.app/api/auth/register -H \"Content-Type: application/json\" -d '{\"email\":\"test@test.com\",\"password\":\"123456\",\"name\":\"Test User\"}'"
echo ""
echo "🏃‍♂️ Quick Deploy with Environment Variables:"
echo "1. Set environment variables in Vercel dashboard"
echo "2. Run: vercel --prod"
echo "3. Test your application"
echo ""
echo "✅ Happy coding! Your Jira-like project management system is ready!"
